export const APPLICATION_NAME = "Website BPM";
export const APPLICATION_ID = "APP58";
export const ROOT_LINK = "http://localhost:5173";
export const API_LINK = "http://localhost:5187";
export const TENTANGFILE_LINK = "http://localhost:5187/Uploads/";
export const BERITAFOTO_LINK = "http://localhost:5187/Berita/";
export const FILE_LINK = "http://localhost:5187/Uploads/";
export const BASE_ROUTE = "";
export const PAGE_SIZE = 10;
